require File.join(File.dirname(`node --print "require.resolve('expo/package.json')"`), "scripts/autolinking")
require File.join(File.dirname(`node --print "require.resolve('react-native/package.json')"`), "scripts/react_native_pods")

require 'json'
podfile_properties = JSON.parse(File.read(File.join(__dir__, 'Podfile.properties.json'))) rescue {}

ENV['RCT_NEW_ARCH_ENABLED'] = '0' if podfile_properties['newArchEnabled'] == 'false'
ENV['EX_DEV_CLIENT_NETWORK_INSPECTOR'] = podfile_properties['EX_DEV_CLIENT_NETWORK_INSPECTOR']

platform :ios, podfile_properties['ios.deploymentTarget'] || '15.1'
install! 'cocoapods',
  :deterministic_uuids => false

prepare_react_native_project!

target 'BearPool' do
  use_expo_modules!

  if ENV['EXPO_USE_COMMUNITY_AUTOLINKING'] == '1'
    config_command = ['node', '-e', "process.argv=['', '', 'config'];require('@react-native-community/cli').run()"];
  else
    config_command = [
      'npx',
      'expo-modules-autolinking',
      'react-native-config',
      '--json',
      '--platform',
      'ios'
    ]
  end

  config = use_native_modules!(config_command)

  use_frameworks! :linkage => podfile_properties['ios.useFrameworks'].to_sym if podfile_properties['ios.useFrameworks']
  use_frameworks! :linkage => ENV['USE_FRAMEWORKS'].to_sym if ENV['USE_FRAMEWORKS']

  use_react_native!(
    :path => config[:reactNativePath],
    :hermes_enabled => podfile_properties['expo.jsEngine'] == nil || podfile_properties['expo.jsEngine'] == 'hermes',
    :app_path => "#{Pod::Config.instance.installation_root}/..",
    :privacy_file_aggregation_enabled => podfile_properties['apple.privacyManifestAggregationEnabled'] != 'false',
  )

  post_install do |installer|
    react_native_post_install(
      installer,
      config[:reactNativePath],
      :mac_catalyst_enabled => false,
      :ccache_enabled => podfile_properties['apple.ccacheEnabled'] == 'true',
    )

    # Ensure Folly flags are set so it doesn't look for coro headers on iOS
    folly_flags = [
      'FOLLY_NO_CONFIG=1',
      'FOLLY_MOBILE=1',
      'FOLLY_USE_LIBCPP=1',
      'FOLLY_HAVE_CLOCK_GETTIME=1',
      'FOLLY_CFG_NO_COROUTINES=1',
      'FOLLY_HAS_COROUTINES=0'
    ]

    installer.pods_project.targets.each do |t|
      t.build_configurations.each do |bc|
        definitions = Array(bc.build_settings['GCC_PREPROCESSOR_DEFINITIONS'])
        definitions << '$(inherited)' if definitions.empty?
        folly_flags.each do |flag|
          definitions << flag unless definitions.include?(flag)
        end
        bc.build_settings['GCC_PREPROCESSOR_DEFINITIONS'] = definitions
      end
    end

    # Xcode 14+: don't sign resource bundles
    installer.target_installation_results.pod_target_installation_results.each do |pod_name, result|
      result.resource_bundle_targets.each do |bundle_target|
        bundle_target.build_configurations.each do |bc|
          bc.build_settings['CODE_SIGNING_ALLOWED'] = 'NO'
        end
      end
    end
  end
end
